### ISSUE TITLE
Launching Issue

### ISSUE THREAD

**Issue by cjlynch278** [SwolfPy-Project/swolfpy#1]
I was able to get the program to run in my conda environment on windows. However, I'm having a bit of trouble on mac. I was able to succesfully configure my conda environment, install swolfpy with pip, and then launch python. However, when import swolfpy, I receive the following error: 
          >>> import swolfpy as sp
          Traceback (most recent call last):
            File "<stdin>", line 1, in <module>
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/swolfpy/__init__.py", line 7, in <module>
              from .Technosphere import Technosphere
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/swolfpy/Technosphere.py", line 7, in <module>
              from brightway2 import Database, projects, bw2setup, databases
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/brightway2/__init__.py", line 2, in <module>
              from bw2data import *
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/bw2data/__init__.py", line 35, in <module>
              from .meta import (
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/bw2data/meta.py", line 186, in <module>
              geomapping = GeoMapping()
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/bw2data/meta.py", line 66, in __init__
              super(GeoMapping, self).__init__(*args, **kwargs)
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/bw2data/serialization.py", line 122, in __init__
              self.load()
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/bw2data/serialization.py", line 127, in load
              self.data = self.deserialize()
            File "/opt/miniconda3/envs/swolfpy/lib/python3.7/site-packages/bw2data/serialization.py", line 240, in deserialize
              return self.unpack(pickle.load(open(self.filepath, "rb")))
          ValueError: unsupported pickle protocol: 5
          
I then tried to configure another conda environment using python 3.9, this seems to have gotten a bit farther but after entering sp.swoflpy() the application starts a python application that isn't visible and I have the following warning: 
          >>> import swolfpy
          >>> swolfpy.swolfpy()
          qt.qpa.fonts: Populating font family aliases took 737 ms. Replace uses of missing font family "MS Shell Dlg 2" with one hat exists to avoid this cost. 
          
I'm a bit of a conda and mac os rookie so any troubleshooting tips would be helpful. Also curious to know if anybody has gotten this to work on mac or if anyone has seen this error. This could be user error, but figured I'd ask for help.

**Comment by msm-sardar** [comment]
The first error is related to bw2data. Check the https://github.com/brightway-lca/brightway2-data/issues/83

I would suggest installing the older versions of Brightway2:
brightway2             2.3
bw2analyzer            0.9.4
bw2calc                1.8.0
bw2data                3.6.2
bw2io                  0.7.12.1

I am a windows user, so I cannot reproduce the error, but I know that the previous versions were working fine on mac. So I suggest downgrading the PySide2. Seems that a lot of people have the same problem with qt fonts on mac but I couldn't find a good solution!

**Comment by msm-sardar** [comment]
@cjlynch278 Uninstall the pyside2 and install pyside2 V5.14. 
```
pip uninstall PySide2
pip install PySide2==5.14
```
Commit https://github.com/SwolfPy-Project/swolfpy/commit/f3fb776f23ca0e00e5f0708c0a594d7a939958c7 sets the version for PySide2.
