### ISSUE TITLE
Issue installing - ModuleNotFoundError. Bug?

### ISSUE THREAD

**Issue by lauriaco** [SwolfPy-Project/swolfpy#10]
Hello, I was following the steps detailed per https://swolfpy.readthedocs.io/en/latest/installation.html on my Macbook Pro (macOS Monterey 12.6.3).

Everything was fine until I tried to run swolfpy in python:
>>> import swolfpy as sp
        sp.swolfpy()

Which produced the attached error response. Not sure if this is a bug or something going wrong on my end? All help or suggestions appreciated!
<img width="843" alt="Screen Shot 2023-08-14 at 11 52 17 AM" src="https://github.com/SwolfPy-Project/swolfpy/assets/142246682/fe8e7cdb-4836-4fc8-86b5-78845bd1f911">

**Comment by lauriaco** [comment]
Text from attachment copied below for reference:

>>> import swolfpy as sp
sp.swolfpy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/LI/miniconda3/envs/swolfpy/lib/python3.9/site-packages/swolfpy/__init__.py", line 7, in <module>
    from .Technosphere import Technosphere
  File "/Users/LI/miniconda3/envs/swolfpy/lib/python3.9/site-packages/swolfpy/Technosphere.py", line 11, in <module>
    from .swolfpy_method import import_methods
  File "/Users/LI/miniconda3/envs/swolfpy/lib/python3.9/site-packages/swolfpy/swolfpy_method.py", line 10, in <module>
    import swolfpy_inputdata.Data.LCIA_Methods as m
ModuleNotFoundError: No module named 'swolfpy_inputdata.Data'
>>> sp.swolfpy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sp' is not defined

**Comment by msm-sardar** [comment]
There was a problem with packaging swolfpy. Try to install the swolfpy in a new environment with Python 3.9. 

```
conda env remove --name swolfpy
conda create --name swolfpy python=3.9 graphviz
pip install swolfpy
```

**Comment by lauriaco** [comment]
That worked - thank you!!
