### ISSUE TITLE
Optimization error

### ISSUE THREAD

**Issue by mert21433** [SwolfPy-Project/swolfpy#6]
Here is an error I encountered while trying the optimize:
-------------------------------------------------------------------------
Optimization setting:

project_name = P1

functional_unit = {('waste', 'S1'): 1}

method = [('IPCC 2013', 'climate change', 'GWP 100a')]

optimize collection scheme = False

number of iterations = 1

number of threads = 8

Initial guess generator = random

Timeout = 1500

constraints = {}
Iteration: 0 PID: 18200

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\swolfpy\Optimization.py", line 413, in abortable_worker
    return(res.get(timeout))  # Wait timeout seconds for func to complete.
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\swolfpy\Optimization.py", line 424, in worker
    res = minimize(optObject._objective_function, x0, method='SLSQP', bounds=bnds, constraints=optObject.cons)
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\scipy\optimize\_minimize.py", line 631, in minimize
    return _minimize_slsqp(fun, x0, args, jac, bounds,
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\scipy\optimize\slsqp.py", line 427, in _minimize_slsqp
    slsqp(m, meq, x, xl, xu, fx, c, g, a, acc, majiter, mode, w, jw,
ValueError: unexpected array size: new_size=1, got array with arr_size=0

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\swolfpy\UI\Workers.py", line 82, in run
    results = Optimization.multi_start_optimization(self.opt,
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\swolfpy\Optimization.py", line 347, in multi_start_optimization
    results = [res.get() for res in all_results]
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\site-packages\swolfpy\Optimization.py", line 347, in <listcomp>
    results = [res.get() for res in all_results]
  File "C:\Users\gokse\anaconda3\envs\swolfpy\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
ValueError: unexpected array size: new_size=1, got array with arr_size=0
-------------------------------------------------------------------------------------------------------------------------
Thank you.

**Comment by mert21433** [comment]
I think I solved it. Optimization settings -> Optimize collection scheme -> Check. I do not have this error  anymore.
